running:
  covariance: nuscenes_2hz
  score_threshold: 0.01
  max_age_since_update: 2
  min_hits_to_birth: 0
  match_type: greedy
  asso: m_dis
  has_velo: false
  motion_model: fbkf
  asso_thres:
    giou: 1.5
    iou: 0.9
    m_dis: 11

redundancy:
  mode: default
  det_score_threshold: 
    iou: 0.01
    giou: 0.01
    m_dis: 0.01
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5
    m_dis: 11

data_loader:
  pc: false