running:
  covariance: nuscenes_2hz
  score_threshold: 0.5
  max_age_since_update: 2
  min_hits_to_birth: 3
  match_type: greedy
  asso: m_dis
  motion_model: fbkf
  asso_thres:
    iou: 0.1
    giou: 1.5
    m_dis: 10

redundancy:
  mode: mm
  det_score_threshold: 
    iou: 0.1
    giou: 0.1
    m_dis: 0.1
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5
    m_dis: 10

data_loader:
  pc: true